FROM maven:3.9.6-eclipse-temurin-21 AS builder

WORKDIR /app
COPY . /app

RUN mvn clean install -DskipTests

FROM sonarsource/sonar-scanner-cli:latest

WORKDIR /app
COPY --from=builder /app /app

CMD ["sonar-scanner", "-Dsonar.projectBaseDir=/app"]
